name: Build and deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # The "build" workflow
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install dependencies
      run: |
        go version

    # Run build of the application
    - name: Run build
      run: go build -v .

    # Run vet & lint on the code
    - name: Run vet & lint
      run: |
        go vet .

    # Run testing on the code
    - name: Run testing
      run: go test -v

  # The "deploy" workflow
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [ build ] # Only run this workflow when "build" workflow succeeds
    # Only run this workflow if it is master branch on push event
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3